services:
  db:
    image: postgres
    container_name: revise-development-db
    environment:
      POSTGRES_DB: ${DB_NAME:-revise}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    env_file:
      - .env