spring:
  application:
    name: revise
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_SERVER_URL}/realms/${KC_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

revise:
  keycloak:
    server-url: ${KC_SERVER_URL}
    realm: ${KC_REALM}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    username: ${KC_USERNAME}
    password: ${KC_PASSWORD}