spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

revise:
  keycloak:
    server-url: ${KC_SERVER_URL}
    realm: ${KC_REALM}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    username: ${KC_USERNAME}
    password: ${KC_PASSWORD}